###*  Get weather forecast 

GET http://127.0.0.1:8080/api/weather-data?lat=-22&lon=-44&lang=en_us

###* Get user city by ip
GET http://127.0.0.1:8080/api/ip-geolocation


###* Get user IP 
http://127.0.0.1:8080/api/ip-geolocation